apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-generator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: exchange-generator
  template:
    metadata:
      labels:
        app: exchange-generator
    spec:
      containers:
        - name: exchange-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.global.spring.profile | default "default" | quote }}
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: exchange-generator-config
                  key: SERVER_PORT
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URL
              valueFrom:
                configMapKeyRef:
                  name: exchange-generator-config
                  key: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URL
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: exchange-generator-config
                  key: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: exchange-generator-config
                  key: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URL
            - name: API_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: exchange-generator-config
                  key: API_EXCHANGE
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: exchange-generator-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EXCHANGE_GENERATOR_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: exchange-generator-secret
                  key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EXCHANGE_GENERATOR_CLIENT_ID
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION__EXCHANGE_GENERATOR_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: exchange-generator-secret
                  key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION__EXCHANGE_GENERATOR_CLIENT_SECRET
