server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework

spring:
  application:
    name: frontend-ui

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URL}
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI}


keycloak-admin:
  server-url: ${KEYCLOAK_ADMIN_SERVER_URL}
  username: ${KEYCLOAK_ADMIN_USERNAME}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm: ${KEYCLOAK_ADMIN_REALM}

api:
  account: ${API_ACCOUNT:http://localhost:8080/api/account}
  cash: ${API_CASH:http://localhost:8080/api/cash}
  transfer: ${API_TRANSFER:http://localhost:8080/api/transfer}
  exchange: ${API_EXCHANGE:http://localhost:8080/api/exchange}