apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: transfer
  template:
    metadata:
      labels:
        app: transfer
    spec:
      containers:
        - name: transfer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.global.spring.profile | default "default" | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
            - name: API_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: API_ACCOUNT
            - name: API_CASH
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: API_CASH
            - name: API_BLOCKER
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: API_BLOCKER
            - name: API_NOTIFICATION
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: API_NOTIFICATION
            - name: API_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: API_EXCHANGE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: SERVER_PORT
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: transfer-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
