apiVersion: v1
kind: ConfigMap
metadata:
  name: cash-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.configMap.jwtIssuerUri | default .Values.global.jwtIssuerUri | quote}}
  SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: {{ .Values.configMap.kafkaBootstrapServers | default .Values.global.kafkaBootstrapServers | quote}}
  API_ACCOUNT: {{ .Values.configMap.api.account | default .Values.global.api.account | quote}}
  API_CASH: {{ .Values.configMap.api.cash | default .Values.global.api.cash | quote}}
  API_BLOCKER: {{ .Values.configMap.api.blocker | default .Values.global.api.blocker | quote}}
  API_NOTIFICATION: {{ .Values.configMap.api.notification | default .Values.global.api.notification | quote}}
  SERVER_PORT: {{ .Values.service.port | quote }}
