apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.global.spring.profile | default "default" | quote }}
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SPRING_MAIL_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SERVER_PORT
