server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: transfer

  kafka:
    producer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8480/realms/bank}

api:
  account: ${API_ACCOUNT:http://localhost:8080/api/account}
  exchange: ${API_EXCHANGE:http://localhost:8080/api/exchange}
  transfer: ${API_TRANSFER:http://localhost:8080/api/transfer}
  blocker: ${API_BLOCKER:http://localhost:8080/api/blocker}
  notification: ${API_NOTIFICATION:http://localhost:8080/api/notification}